# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9683cb7333303b9b85467b4f7a09952122df75e1149665fd4d2365bc1f09cf5998b02ec2b4cdc33700befa29f6a9372d9b56f5ac64ac515089700c0ff1fc8655

test:
  secret_key_base: 588bfc770e9cb18e0ffe26e26c49b1a17a13d042e176d68cf94eb3bef18a1e5647c3901a4524312f8e0569a091f125b9a8501ef515797d20e4777297b545a6be

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
